config/routes.rb
Rails.application.routes.draw do
  resources :tipos
  resources :ambientes
  resources :bichos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ambiente.rb
class Ambiente < ApplicationRecord

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicho.rb
class Bicho < ApplicationRecord
    belongs_to :ambiente

    has_many :bicho_tipos
    has_many :tipos, through: :bicho_tipos
    
end

app/models/bicho_tipo.rb
class BichoTipo < ApplicationRecord
  belongs_to :bicho
  belongs_to :tipo
end

app/models/tipo.rb
class Tipo < ApplicationRecord

    has_many :bicho_tipos
    has_many :bichos, through: :bicho_tipos

end

app/controllers/ambientes_controller.rb
class AmbientesController < ApplicationController
  before_action :set_ambiente, only: [:show, :edit, :update, :destroy]

  # GET /ambientes
  # GET /ambientes.json
  def index
    @ambientes = Ambiente.all
  end

  # GET /ambientes/1
  # GET /ambientes/1.json
  def show
  end

  # GET /ambientes/new
  def new
    @ambiente = Ambiente.new
  end

  # GET /ambientes/1/edit
  def edit
  end

  # POST /ambientes
  # POST /ambientes.json
  def create
    @ambiente = Ambiente.new(ambiente_params)

    respond_to do |format|
      if @ambiente.save
        format.html { redirect_to @ambiente, notice: 'Ambiente was successfully created.' }
        format.json { render :show, status: :created, location: @ambiente }
      else
        format.html { render :new }
        format.json { render json: @ambiente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ambientes/1
  # PATCH/PUT /ambientes/1.json
  def update
    respond_to do |format|
      if @ambiente.update(ambiente_params)
        format.html { redirect_to @ambiente, notice: 'Ambiente was successfully updated.' }
        format.json { render :show, status: :ok, location: @ambiente }
      else
        format.html { render :edit }
        format.json { render json: @ambiente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ambientes/1
  # DELETE /ambientes/1.json
  def destroy
    @ambiente.destroy
    respond_to do |format|
      format.html { redirect_to ambientes_url, notice: 'Ambiente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ambiente
      @ambiente = Ambiente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ambiente_params
      params.require(:ambiente).permit(:nome)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bichos_controller.rb
class BichosController < ApplicationController
  before_action :set_bicho, only: [:show, :edit, :update, :destroy]

  # GET /bichos
  # GET /bichos.json
  def index
    @bichos = Bicho.all
  end

  # GET /bichos/1
  # GET /bichos/1.json
  def show
  end

  # GET /bichos/new
  def new
    @bicho = Bicho.new
  end

  # GET /bichos/1/edit
  def edit
  end

  # POST /bichos
  # POST /bichos.json
  def create
    @bicho = Bicho.new(bicho_params)

    respond_to do |format|
      if @bicho.save
        format.html { redirect_to @bicho, notice: 'Bicho was successfully created.' }
        format.json { render :show, status: :created, location: @bicho }
      else
        format.html { render :new }
        format.json { render json: @bicho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bichos/1
  # PATCH/PUT /bichos/1.json
  def update
    respond_to do |format|
      if @bicho.update(bicho_params)
        format.html { redirect_to @bicho, notice: 'Bicho was successfully updated.' }
        format.json { render :show, status: :ok, location: @bicho }
      else
        format.html { render :edit }
        format.json { render json: @bicho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bichos/1
  # DELETE /bichos/1.json
  def destroy
    @bicho.destroy
    respond_to do |format|
      format.html { redirect_to bichos_url, notice: 'Bicho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bicho
      @bicho = Bicho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bicho_params
      params.require(:bicho).permit(:nome, :alimentacao, :ambiente_id, :tipos_id => [])
    end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]

  # GET /tipos
  # GET /tipos.json
  def index
    @tipos = Tipo.all
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: 'Tipo was successfully created.' }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1
  # PATCH/PUT /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to @tipo, notice: 'Tipo was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: 'Tipo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_params
      params.require(:tipo).permit(:nome)
    end
end

app/helpers/ambientes_helper.rb
module AmbientesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bichos_helper.rb
module BichosHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/ambientes/_form.html.erb
<%= form_with(model: ambiente, local: true) do |form| %>
  <% if ambiente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ambiente.errors.count, "error") %> prohibited this ambiente from being saved:</h2>

      <ul>
        <% ambiente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ambientes/edit.html.erb
<h1>Editing Ambiente</h1>

<%= render 'form', ambiente: @ambiente %>

<%= link_to 'Show', @ambiente %> |
<%= link_to 'Back', ambientes_path %>

app/views/ambientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ambientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ambientes.each do |ambiente| %>
      <tr>
        <td><%= ambiente.nome %></td>
        <td><%= link_to 'Show', ambiente %></td>
        <td><%= link_to 'Edit', edit_ambiente_path(ambiente) %></td>
        <td><%= link_to 'Destroy', ambiente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ambiente', new_ambiente_path %>

app/views/ambientes/new.html.erb
<h1>New Ambiente</h1>

<%= render 'form', ambiente: @ambiente %>

<%= link_to 'Back', ambientes_path %>

app/views/ambientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @ambiente.nome %>
</p>

<%= link_to 'Edit', edit_ambiente_path(@ambiente) %> |
<%= link_to 'Back', ambientes_path %>

app/views/bichos/_form.html.erb
<%= form_with(model: bicho, local: true) do |form| %>
  <% if bicho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bicho.errors.count, "error") %> prohibited this bicho from being saved:</h2>

      <ul>
        <% bicho.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :ambiente %>
  <%= collection_select(:bicho, :ambiente_id, Ambiente.all, :id, :nome) %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :alimentacao %>
    <%= form.text_field :alimentacao %>
  </div>

  <div class="field">
  <%= form.label :tipo %>
  <%= collection_check_boxes(:bicho, :tipo_ids, Tipo.all, :id, :nome) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bichos/edit.html.erb
<h1>Editing Bicho</h1>

<%= render 'form', bicho: @bicho %>

<%= link_to 'Show', @bicho %> |
<%= link_to 'Back', bichos_path %>

app/views/bichos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bichos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Ambiente</th>
      <th>Alimentacao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bichos.each do |bicho| %>
      <tr>
        <td><%= bicho.nome %></td>
        <td><%= bicho.ambiente %></td>
        <td><%= bicho.alimentacao %></td>
        <td><%= link_to 'Show', bicho %></td>
        <td><%= link_to 'Edit', edit_bicho_path(bicho) %></td>
        <td><%= link_to 'Destroy', bicho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bicho', new_bicho_path %>

app/views/bichos/new.html.erb
<h1>New Bicho</h1>

<%= render 'form', bicho: @bicho %>

<%= link_to 'Back', bichos_path %>

app/views/bichos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @bicho.nome %>
</p>

<p>
  <strong>Alimentacao:</strong>
  <%= @bicho.alimentacao %>
</p>

<%= link_to 'Edit', edit_bicho_path(@bicho) %> |
<%= link_to 'Back', bichos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="menu">
    <%= link_to "BICHOS", bichos_path %>
    <%= link_to "AMBIENTES", ambientes_path %>
    <%= link_to "TIPOS", tipos_path %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/tipos/_form.html.erb
<%= form_with(model: tipo, local: true) do |form| %>
  <% if tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

      <ul>
        <% tipo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tipos/edit.html.erb
<h1>Editing Tipo</h1>

<%= render 'form', tipo: @tipo %>

<%= link_to 'Show', @tipo %> |
<%= link_to 'Back', tipos_path %>

app/views/tipos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipos.each do |tipo| %>
      <tr>
        <td><%= tipo.nome %></td>
        <td><%= link_to 'Show', tipo %></td>
        <td><%= link_to 'Edit', edit_tipo_path(tipo) %></td>
        <td><%= link_to 'Destroy', tipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo', new_tipo_path %>

app/views/tipos/new.html.erb
<h1>New Tipo</h1>

<%= render 'form', tipo: @tipo %>

<%= link_to 'Back', tipos_path %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @tipo.nome %>
</p>

<%= link_to 'Edit', edit_tipo_path(@tipo) %> |
<%= link_to 'Back', tipos_path %>